version: "3.7"
services:
  pgadmin:
    image: dpage/pgadmin4:4.27
    environment:
      PGADMIN_DEFAULT_PASSWORD : secret
      PGADMIN_DEFAULT_EMAIL : abdeljalil.aitetaleb@gmail.com
    ports:
      - "8080:80"
  db_esna:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: root
      POSTGRES_DB: najoualearn
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data