export const LOAD_ANNONCES = "LOAD_ANNONCES";
export const LOAD_FORMATIONS ="LOAD_FORMATIONS";
export const LOAD_MODULES ="LOAD_MODULES";
export const LOAD_COURSES ="LOAD_COURSES";
export const LOAD_DEPARTEMENT ="LOAD_DEPARTEMENT";
export const LOAD_STUDENTS ="LOAD_STUDENTS";
export const LOAD_FORMATEURS ="LOAD_FORMATEURS";
export const LOAD_TICKETS ="LOAD_TICKETS";
export const LOAD_MESSAGES ="LOAD_MESSAGES";


export const IS_LOADING = "IS_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
